<?php

namespace App\Controllers\Api;

use App\Controllers\BaseController;
use App\Models\TestModel;
use App\Models\TestAttemptModel;
use App\Models\TestLogModel;
use App\Models\TestLogAnswerModel;
use App\Models\QuestionModel;
use App\Models\AnswerModel;
use App\Models\ActivityLogModel;

class ExamApiController extends BaseController
{
    protected TestModel $testModel;
    protected TestAttemptModel $attemptModel;
    protected ActivityLogModel $activityLog;

    public function __construct()
    {
        $this->testModel = new TestModel();
        $this->attemptModel = new TestAttemptModel();
        $this->activityLog = new ActivityLogModel();
    }

    /**
     * Initialize exam: authenticate, start attempt if needed, return questions JSON
     * POST /api/exam/init
     */
    public function init()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error', 'message' => 'Silakan login terlebih dahulu.']);
        }

        $testId = $this->request->getPost('test_id') ?? $this->request->getGet('test_id');
        if (!$testId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'test_id diperlukan.']);
        }

        $test = $this->testModel->find($testId);
        if (!$test || !$test->is_enabled) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Ujian tidak tersedia.']);
        }

        // Check time boundaries
        $now = date('Y-m-d H:i:s');
        if ($test->begin_time && $now < $test->begin_time) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Ujian belum dimulai.']);
        }
        if ($test->end_time && $now > $test->end_time) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Waktu ujian telah berakhir.']);
        }

        // Check for active attempt
        $attempt = $this->attemptModel->getActiveAttempt($testId, $userId);

        if (!$attempt) {
            // Attempt must be generated by the backend prepare/start flow first
            return $this->response->setJSON(['status' => 'need_prepare']);
        }

        // Load questions and answers
        $db = \Config\Database::connect();
        $questions = $db->query("
            SELECT tl.*, tl.id as log_id
            FROM test_logs tl
            WHERE tl.test_attempt_id = ?
            ORDER BY tl.display_order ASC
        ", [$attempt->id])->getResult();

        $logIds = array_column($questions, 'log_id');
        $answers = [];
        if (!empty($logIds)) {
            $rawAnswers = $db->query("
                SELECT tla.*, tla.id as log_answer_id
                FROM test_log_answers tla
                WHERE tla.test_log_id IN ?
                ORDER BY tla.display_order ASC
            ", [$logIds])->getResult();
            foreach ($rawAnswers as $ans) {
                $answers[$ans->test_log_id][] = $ans;
            }
        }

        // Merge Redis cached answers
        try {
            $redis = new \Redis();
            if ($redis->connect('redis', 6379)) {
                $redisKey = "exam_answers:{$attempt->id}";
                $redisAnswers = $redis->hGetAll($redisKey);
                if (!empty($redisAnswers)) {
                    foreach ($questions as &$q) {
                        if (isset($redisAnswers[$q->log_id])) {
                            $saved = json_decode($redisAnswers[$q->log_id], true);
                            if ($q->question_type == 3) {
                                $q->answer_text = $saved['answer_text'] ?? '';
                            } elseif ($q->question_type == 4 || $q->question_type == 5) {
                                $q->answer_text = json_encode($saved['matching_answers'] ?? []);
                            } else {
                                $selectedIds = $saved['selected_answers'] ?? [];
                                if (isset($answers[$q->log_id])) {
                                    foreach ($answers[$q->log_id] as &$ans) {
                                        $ans->is_selected = in_array($ans->answer_id, $selectedIds) ? 1 : 0;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } catch (\Exception $e) {}

        // Build response
        $questionsData = [];
        $answersData = [];
        foreach ($questions as $q) {
            $qAnswers = [];
            if (isset($answers[$q->log_id])) {
                foreach ($answers[$q->log_id] as $a) {
                    $qAnswers[] = [
                        'log_answer_id' => (int)$a->log_answer_id,
                        'answer_id' => (int)$a->answer_id,
                        'answer_text' => $a->answer_text,
                        'display_order' => (int)$a->display_order,
                        'is_selected' => (int)$a->is_selected,
                    ];
                }
            }
            if ($test->exam_mode === 'static') {
                $answersData[$q->question_id] = $qAnswers;
                $questionsData[] = [
                    'question_id' => (int)$q->question_id,
                    'answer_text' => $q->answer_text,
                ];
            } else {
                $answersData[$q->log_id] = $qAnswers;
                
                $questionsData[] = [
                    'log_id' => (int)$q->log_id,
                    'question_text' => $q->question_text,
                    'question_type' => (int)$q->question_type,
                    'display_order' => (int)$q->display_order,
                    'num_answers' => (int)$q->num_answers,
                    'answer_text' => $q->answer_text,
                    'is_unsure' => (int)($q->is_unsure ?? 0),
                ];
            }
        }

        // Load anti-cheat settings
        $settingModel = new \App\Models\SettingModel();

        return $this->response->setJSON([
            'status' => 'success',
            'attempt_id' => (int)$attempt->id,
            'user' => [
                'id' => (int)$userId,
                'username' => session('username'),
                'firstname' => session('firstname'),
                'lastname' => session('lastname'),
            ],
            'test' => [
                'id' => (int)$test->id,
                'name' => $test->name,
                'duration_minutes' => (int)$test->duration_minutes,
                'passing_score' => (float)$test->passing_score,
                'max_score' => (float)$test->max_score,
                'show_menu' => (int)$test->show_menu,
                'allow_noanswer' => (int)$test->allow_noanswer,
                'auto_logout_on_timeout' => (int)$test->auto_logout_on_timeout,
                'started_at' => $attempt->started_at,
                'started_at_ms' => strtotime($attempt->started_at) * 1000,
                'begin_time_ms' => strtotime($test->begin_time) * 1000,
                'server_now_ms' => time() * 1000,
                'exam_mode' => $test->exam_mode,
                'static_page_path' => $test->static_page_path,
            ],
            'anti_cheat' => [
                'enabled' => (bool)$settingModel->getValue('anti_cheat_enabled', false),
                'max_strikes' => (int)$settingModel->getValue('max_cheat_strikes', 2),
                'suspend_timer' => (int)$settingModel->getValue('suspend_timer_seconds', 30),
                'current_strikes' => (int)($attempt->cheat_strikes ?? 0),
                'title' => $settingModel->getValue('anti_cheat_title', '⚠️ Peringatan Kecurangan!'),
                'message' => $settingModel->getValue('anti_cheat_message', 'Sistem mendeteksi Anda meninggalkan halaman ujian.'),
                'logo' => $settingModel->getValue('anti_cheat_logo', ''),
            ],
            'questions' => $questionsData,
            'answers' => $answersData,
            'csrf_token' => csrf_hash(),
            'csrf_name' => csrf_token(),
        ]);
    }

    /**
     * Generate exam attempt (reused from ExamController::start logic)
     */
    private function generateExam($test, $userId)
    {
        $db = \Config\Database::connect();
        $db->transStart();

        $this->attemptModel->insert([
            'test_id' => $test->id,
            'user_id' => $userId,
            'status' => 1,
            'started_at' => date('Y-m-d H:i:s'),
        ]);
        $attemptId = $this->attemptModel->getInsertID();

        $sets = $db->table('test_subject_sets')->where('test_id', $test->id)->get()->getResult();
        $answerModel = new AnswerModel();
        $testLogModel = new TestLogModel();
        $testLogAnswerModel = new TestLogAnswerModel();
        $displayOrder = 1;

        foreach ($sets as $set) {
            $subjects = $db->table('test_subjects')->where('test_subject_set_id', $set->id)->get()->getResultArray();
            $subjectIds = array_column($subjects, 'subject_id');
            if (empty($subjectIds)) continue;

            $qBuilder = $db->table('questions')->whereIn('subject_id', $subjectIds)->where('is_enabled', 1);
            if ($set->question_type != 0) $qBuilder->where('type', $set->question_type);
            if ($set->difficulty != 0) $qBuilder->where('difficulty', $set->difficulty);

            if ($test->exam_mode === 'static') {
                $questions = $qBuilder->orderBy("RAND({$test->id})")->limit($set->quantity)->get()->getResult();
            } else {
                $questions = $qBuilder->orderBy('RAND()')->limit($set->quantity)->get()->getResult();
            }

            foreach ($questions as $q) {
                $testLogModel->insert([
                    'test_attempt_id' => $attemptId,
                    'question_id' => $q->id,
                    'question_text' => $q->description,
                    'question_type' => $q->type,
                    'question_difficulty' => $q->difficulty,
                    'display_order' => $displayOrder,
                    'num_answers' => $set->num_answers ?: 0,
                    'user_ip' => $this->request->getIPAddress(),
                ]);
                $testLogId = $testLogModel->getInsertID();

                $answers = $answerModel->getAnswersByQuestion($q->id);
                if ($test->random_answers && in_array($q->type, [1, 2])) {
                    if ($test->exam_mode === 'static') {
                        mt_srand($test->id + $q->id);
                        shuffle($answers);
                        mt_srand();
                    } else {
                        shuffle($answers);
                    }
                }

                $ansOrder = 1;
                foreach ($answers as $ans) {
                    $testLogAnswerModel->insert([
                        'test_log_id' => $testLogId,
                        'answer_id' => $ans->id,
                        'answer_text' => $ans->description,
                        'is_correct' => $ans->is_correct,
                        'display_order' => $ansOrder,
                        'position' => $ans->position,
                        'is_selected' => 0,
                    ]);
                    $ansOrder++;
                }
                $displayOrder++;
            }
        }

        if ($test->random_questions) {
            $logs = $testLogModel->where('test_attempt_id', $attemptId)->findAll();
            if ($test->exam_mode === 'static') {
                mt_srand($test->id);
                shuffle($logs);
                mt_srand();
            } else {
                shuffle($logs);
            }
            $newOrder = 1;
            foreach ($logs as $l) {
                $testLogModel->update($l->id, ['display_order' => $newOrder]);
                $newOrder++;
            }
        }

        $db->transComplete();
        if ($db->transStatus() === false) return null;

        $this->activityLog->log('start_test', $userId, 'test', $test->id, "Memulai ujian (static): {$test->name}");
        return $this->attemptModel->find($attemptId);
    }

    /**
     * Save answer via AJAX (same as ExamController::saveAnswer but JSON-only)
     * POST /api/exam/autosave
     */
    public function autosave()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error', 'message' => 'Unauthorized']);
        }

        $logId = $this->request->getPost('log_id');
        $questionId = $this->request->getPost('question_id');
        $attemptIdParam = $this->request->getPost('attempt_id');
        $questionType = $this->request->getPost('question_type');

        $testLogModel = new TestLogModel();
        
        if ($logId) {
            $log = $testLogModel->find($logId);
        } elseif ($questionId && $attemptIdParam) {
            $log = $testLogModel->where('test_attempt_id', $attemptIdParam)
                                ->where('question_id', $questionId)
                                ->first();
        } else {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Missing identifiers']);
        }
        
        if (!$log) return $this->response->setJSON(['status' => 'error']);
        $logId = $log->id;

        $attempt = $this->attemptModel->find($log->test_attempt_id);
        if (!$attempt || (string)$attempt->user_id !== (string)$userId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Unauthorized']);
        }

        if ($attempt->status == 3) {
            return $this->response->setJSON(['status' => 'kicked', 'message' => 'Ujian telah diselesaikan.']);
        }
        if ($attempt->status == 4) {
            return $this->response->setJSON(['status' => 'kicked', 'message' => 'Ujian telah dikunci.']);
        }

        session_write_close();

        $payload = [];
        if ($questionType == 3) {
            $payload['answer_text'] = $this->request->getPost('answer_text');
        } elseif ($questionType == 4 || $questionType == 5) {
            $payload['matching_answers'] = json_decode($this->request->getPost('matching_answers_json') ?? '{}', true) ?: [];
        } else {
            $selectedIds = $this->request->getPost('selected_answers') ?? [];
            if (!is_array($selectedIds)) $selectedIds = [$selectedIds];
            $payload['selected_answers'] = $selectedIds;
        }

        $attemptId = $log->test_attempt_id;
        $redisKey = "exam_answers:{$attemptId}";

        try {
            $redis = new \Redis();
            if ($redis->connect('redis', 6379)) {
                $redis->hSet($redisKey, $logId, json_encode($payload));
                $redis->expire($redisKey, 86400);
            }
        } catch (\Exception $e) {
            return $this->response->setJSON(['status' => 'error', 'message' => $e->getMessage()]);
        }

        $testLogModel->update($logId, ['answered_at' => date('Y-m-d H:i:s')]);

        return $this->response->setJSON(['status' => 'success', 'csrf_token' => csrf_hash()]);
    }

    /**
     * Auto-sync Redis to DB
     * POST /api/exam/auto-sync
     */
    public function autoSync()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $attemptId = $this->request->getPost('attempt_id');
        session_write_close();

        $attempt = $this->attemptModel->where('id', $attemptId)->where('user_id', $userId)->first();
        if (!$attempt) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Invalid attempt.']);
        }

        $this->flushRedisAnswersToDb($attemptId);
        
        $testModel = new \App\Models\TestModel();
        $test = $testModel->find($attempt->test_id);

        return $this->response->setJSON([
            'status' => 'success',
            'exam_mode' => $test ? $test->exam_mode : 'normal',
            'static_page_path' => $test ? $test->static_page_path : null
        ]);
    }

    /**
     * Finish exam
     * POST /api/exam/finish
     */
    public function finish()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $testId = $this->request->getPost('test_id');
        $attempt = $this->attemptModel->getActiveAttempt($testId, $userId);

        if ($attempt) {
            $this->flushRedisAnswersToDb($attempt->id);
            $scorer = new \App\Libraries\ScoringEngine();
            $scorer->calculateAndSaveScore($attempt->id);
            $this->activityLog->log('finish_test', $userId, 'test', $testId, 'Menyelesaikan ujian (static)');
        }

        return $this->response->setJSON(['status' => 'success', 'message' => 'Ujian berhasil diselesaikan!']);
    }

    /**
     * Check current score
     * POST /api/exam/check-score
     */
    public function checkScore()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $attemptId = $this->request->getPost('attempt_id');
        session_write_close();

        $attempt = $this->attemptModel->where('id', $attemptId)->where('user_id', $userId)->first();
        if (!$attempt) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Invalid attempt.']);
        }

        $this->flushRedisAnswersToDb($attemptId);
        $scorer = new \App\Libraries\ScoringEngine();
        $score = $scorer->calculateScorePreview($attemptId);

        return $this->response->setJSON(['status' => 'success', 'score' => $score]);
    }

    /**
     * Report cheating
     * POST /api/exam/report-cheat
     */
    public function reportCheat()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $attemptId = $this->request->getPost('attempt_id');
        $cheatType = $this->request->getPost('type') ?? 'unknown';

        $attempt = $this->attemptModel->where('id', $attemptId)->where('user_id', $userId)->whereIn('status', [0, 1, 2])->first();
        if (!$attempt) {
            return $this->response->setJSON(['status' => 'error', 'action' => 'kick', 'message' => 'Sesi ujian tidak valid.']);
        }

        $settingModel = new \App\Models\SettingModel();
        $isAntiCheatEnabled = $settingModel->getValue('anti_cheat_enabled', false);
        if (!$isAntiCheatEnabled) {
            return $this->response->setJSON(['status' => 'success', 'action' => 'none']);
        }

        $maxStrikes = (int) $settingModel->getValue('max_cheat_strikes', 2);
        $suspendTimer = (int) $settingModel->getValue('suspend_timer_seconds', 30);
        $forceLogout = (bool) $settingModel->getValue('anti_cheat_force_logout', false);
        $currentStrikes = (int) $attempt->cheat_strikes + 1;

        if ($cheatType === 'tab_switch' || $currentStrikes >= $maxStrikes || $forceLogout) {
            $this->attemptModel->update($attemptId, ['cheat_strikes' => $currentStrikes, 'status' => 2]);
            $userModel = new \App\Models\UserModel();
            $userModel->update($userId, ['is_active' => 0]);

            try {
                $redis = new \Redis();
                if ($redis->connect('redis', 6379)) {
                    $redis->del("user_session:{$userId}");
                    $redis->setex("ban_signal:{$userId}", 120, '1');
                }
            } catch (\Exception $e) {}
            session()->destroy();

            $reason = $forceLogout ? 'melakukan pelanggaran saat ujian (Auto-Lock)' :
                      ($cheatType === 'tab_switch' ? 'mengganti tab' : 'melewati batas peringatan');

            $this->activityLog->log('exam_locked', $userId, 'test', $attempt->test_id,
                "INSTANT BAN (static): Siswa $reason (Strike: $currentStrikes)");

            return $this->response->setJSON([
                'status' => 'success', 'action' => 'lock',
                'message' => "Ujian dikunci karena Anda terdeteksi $reason."
            ]);
        } else {
            $this->attemptModel->update($attemptId, ['cheat_strikes' => $currentStrikes]);
            $this->activityLog->log('exam_suspended', $userId, 'test', $attempt->test_id,
                "WARNING (static): Siswa keluar fullscreen (Strike: $currentStrikes)");

            return $this->response->setJSON([
                'status' => 'success', 'action' => 'suspend',
                'timer' => $suspendTimer, 'strike' => $currentStrikes
            ]);
        }
    }

    /**
     * SSE Stream (proxy to existing SseController logic)
     * GET /api/exam/stream/{attemptId}
     */
    public function stream($attemptId)
    {
        $userId = session('user_id');
        if (!$userId) {
            header('HTTP/1.1 401 Unauthorized');
            exit;
        }

        $attempt = $this->attemptModel->find($attemptId);
        if (!$attempt || (string)$attempt->user_id !== (string)$userId) {
            header('HTTP/1.1 403 Forbidden');
            exit;
        }

        // Redirect to existing SSE controller
        // The SSE endpoint is the same, just needs to handle CORS
        header('Access-Control-Allow-Origin: *');
        header('Access-Control-Allow-Credentials: true');

        // Delegate to existing SseController
        $sseController = new \App\Controllers\Student\SseController();
        return $sseController->stream($attemptId);
    }

    /**
     * Flush Redis answers to DB (same as ExamController)
     */
    private function flushRedisAnswersToDb($attemptId)
    {
        try {
            $redis = new \Redis();
            if ($redis->connect('redis', 6379)) {
                $redisKey = "exam_answers:{$attemptId}";
                $answers = $redis->hGetAll($redisKey);
                if (empty($answers)) return;

                $db = \Config\Database::connect();
                $db->transStart();

                foreach ($answers as $logId => $payloadJson) {
                    $payload = json_decode($payloadJson, true);
                    if (isset($payload['answer_text'])) {
                        $db->table('test_logs')->where('id', $logId)->update(['answer_text' => $payload['answer_text']]);
                    } elseif (isset($payload['matching_answers'])) {
                        $db->table('test_logs')->where('id', $logId)->update(['answer_text' => json_encode($payload['matching_answers'])]);
                    } elseif (isset($payload['selected_answers'])) {
                        $selectedIds = $payload['selected_answers'];
                        $db->table('test_log_answers')->where('test_log_id', $logId)->update(['is_selected' => 0]);
                        if (!empty($selectedIds)) {
                            $db->table('test_log_answers')->where('test_log_id', $logId)->whereIn('answer_id', $selectedIds)->update(['is_selected' => 1]);
                        }
                    }
                }

                $db->transComplete();
                if ($db->transStatus() !== false) {
                    $redis->del($redisKey);
                }
            }
        } catch (\Exception $e) {
            log_message('error', 'Redis flush failed (API): ' . $e->getMessage());
        }
    }
}
