<?php

namespace App\Controllers\Api;

use App\Controllers\BaseController;
use App\Models\TestModel;
use App\Models\TestAttemptModel;
use App\Models\TestLogModel;
use App\Models\TestLogAnswerModel;
use App\Models\QuestionModel;
use App\Models\AnswerModel;
use App\Models\ActivityLogModel;

class ExamApiController extends BaseController
{
    protected TestModel $testModel;
    protected TestAttemptModel $attemptModel;
    protected ActivityLogModel $activityLog;

    public function __construct()
    {
        $this->testModel = new TestModel();
        $this->attemptModel = new TestAttemptModel();
        $this->activityLog = new ActivityLogModel();
    }

    /**
     * Initialize exam: authenticate, start attempt if needed, return questions JSON
     * POST /api/exam/init
     */
    public function init()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error', 'message' => 'Silakan login terlebih dahulu.']);
        }

        $testId = $this->request->getPost('test_id') ?? $this->request->getGet('test_id');
        if (!$testId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'test_id diperlukan.']);
        }

        $test = $this->testModel->findCached($testId);
        if (!$test || !$test->is_enabled) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Ujian tidak tersedia.']);
        }

        // Check time boundaries
        $now = date('Y-m-d H:i:s');
        if ($test->begin_time && $now < $test->begin_time) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Ujian belum dimulai.']);
        }
        if ($test->end_time && $now > $test->end_time) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Waktu ujian telah berakhir.']);
        }

        // Check for active attempt
        $attempt = $this->attemptModel->getActiveAttemptCached($testId, $userId);

        if (!$attempt) {
            // Attempt must be generated by the backend prepare/start flow first
            return $this->response->setJSON(['status' => 'need_prepare']);
        }

        // Load questions and answers
        $db = \Config\Database::connect();
        $cache = service('cache');
        $questionsKey = "attempt_questions_{$attempt->id}";
        $questions = $cache->get($questionsKey);
        if ($questions === null) {
            $questions = $db->query("
                SELECT tl.*, tl.id as log_id
                FROM test_logs tl
                WHERE tl.test_attempt_id = ?
                ORDER BY tl.display_order ASC
            ", [$attempt->id])->getResult();
            try {
                $cache->save($questionsKey, $questions, 7200); // 2 hours
            } catch (\Exception $e) {}
        }

        $logIds = array_column($questions, 'log_id');
        $answers = [];
        if (!empty($logIds)) {
            $answersKey = "attempt_answers_{$attempt->id}";
            $answers = $cache->get($answersKey);
            if ($answers === null) {
                $rawAnswers = $db->query("
                    SELECT tla.*, tla.id as log_answer_id
                    FROM test_log_answers tla
                    WHERE tla.test_log_id IN ?
                    ORDER BY tla.display_order ASC
                ", [$logIds])->getResult();
                $answers = [];
                foreach ($rawAnswers as $ans) {
                    $answers[$ans->test_log_id][] = $ans;
                }
                try {
                    $cache->save($answersKey, $answers, 7200); // 2 hours
                } catch (\Exception $e) {}
            }
        }

        // Merge Redis cached answers
        try {
            $redis = \App\Libraries\RedisClient::getInstance();
            if ($redis) {
                $redisKey = "exam_answers:{$attempt->id}";
                $redisAnswers = $redis->hGetAll($redisKey);
                if (!empty($redisAnswers)) {
                    foreach ($questions as &$q) {
                        if (isset($redisAnswers[$q->log_id])) {
                            $saved = json_decode($redisAnswers[$q->log_id], true);
                            if ($q->question_type == 3) {
                                $q->answer_text = $saved['answer_text'] ?? '';
                            } elseif ($q->question_type == 4 || $q->question_type == 5) {
                                $q->answer_text = json_encode($saved['matching_answers'] ?? []);
                            } else {
                                $selectedIds = $saved['selected_answers'] ?? [];
                                if (isset($answers[$q->log_id])) {
                                    foreach ($answers[$q->log_id] as &$ans) {
                                        $ans->is_selected = in_array($ans->answer_id, $selectedIds) ? 1 : 0;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } catch (\Exception $e) {
            log_message('error', 'Redis integration error in ExamApiController::take: ' . $e->getMessage());
        }

        // Build response
        $questionsData = [];
        $answersData = [];
        foreach ($questions as $q) {
            $qAnswers = [];
            if (isset($answers[$q->log_id])) {
                foreach ($answers[$q->log_id] as $a) {
                    $qAnswers[] = [
                        'log_answer_id' => (int)$a->log_answer_id,
                        'answer_id' => (int)$a->answer_id,
                        'answer_text' => $a->answer_text,
                        'display_order' => (int)$a->display_order,
                        'is_selected' => (int)$a->is_selected,
                    ];
                }
            }
            if ($test->exam_mode === 'static') {
                $answersData[$q->question_id] = $qAnswers;
                $questionsData[] = [
                    'question_id' => (int)$q->question_id,
                    'answer_text' => $q->answer_text,
                ];
            } else {
                $answersData[$q->log_id] = $qAnswers;
                
                $questionsData[] = [
                    'log_id' => (int)$q->log_id,
                    'question_text' => $q->question_text,
                    'question_type' => (int)$q->question_type,
                    'display_order' => (int)$q->display_order,
                    'num_answers' => (int)$q->num_answers,
                    'answer_text' => $q->answer_text,
                    'is_unsure' => (int)($q->is_unsure ?? 0),
                ];
            }
        }

        // Load user to check active status
        $userModel = new \App\Models\UserModel();
        $user = $userModel->find($userId);

        if (!$user || !(int)$user->is_active) {
            return $this->response->setStatusCode(403)->setJSON([
                'status' => 'error',
                'message' => 'Akun tidak aktif. Silakan hubungi pengawas ujian.',
                'action' => 'logout',
            ]);
        }

        $unbannedAtMs = !empty($user->unbanned_at) ? strtotime($user->unbanned_at) * 1000 : null;

        return $this->response->setJSON([
            'status' => 'success',
            'attempt_id' => (int)$attempt->id,
            'user' => [
                'id' => (int)$userId,
                'username' => session('username'),
                'firstname' => session('firstname'),
                'lastname' => session('lastname'),
                'is_active' => (bool)$user->is_active,
                'unbanned_at' => $user->unbanned_at,
                'unbanned_at_ms' => $unbannedAtMs,
            ],
            'test' => [
                'id' => (int)$test->id,
                'name' => $test->name,
                'duration_minutes' => (int)$test->duration_minutes,
                'passing_score' => (float)$test->passing_score,
                'max_score' => (float)$test->max_score,
                'show_menu' => (int)$test->show_menu,
                'allow_noanswer' => (int)$test->allow_noanswer,
                'auto_logout_on_timeout' => (int)$test->auto_logout_on_timeout,
                'started_at' => $attempt->started_at,
                'started_at_ms' => strtotime($attempt->started_at) * 1000,
                'begin_time_ms' => strtotime($test->begin_time) * 1000,
                'server_now_ms' => time() * 1000,
                'exam_mode' => $test->exam_mode,
                'static_page_path' => $test->static_page_path,
            ],
            'questions' => $questionsData,
            'answers' => $answersData,
            'csrf_token' => csrf_hash(),
            'csrf_name' => csrf_token(),
        ]);
    }



    /**
     * Save answer via AJAX (same as ExamController::saveAnswer but JSON-only)
     * POST /api/exam/autosave
     */
    public function autosave()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error', 'message' => 'Unauthorized']);
        }

        $logId = $this->request->getPost('log_id');
        $questionId = $this->request->getPost('question_id');
        $attemptIdParam = $this->request->getPost('attempt_id');
        $questionType = $this->request->getPost('question_type');

        $testLogModel = new TestLogModel();
        
        if ($logId) {
            $log = $testLogModel->findCached($logId);
        } elseif ($questionId && $attemptIdParam) {
            $cache = service('cache');
            $cachedQuestions = $cache->get("attempt_questions_{$attemptIdParam}");
            if ($cachedQuestions) {
                foreach ($cachedQuestions as $q) {
                    if ((string)($q->question_id ?? '') === (string)$questionId) {
                        $log = $q;
                        if (!isset($log->id) && isset($log->log_id)) {
                            $log->id = $log->log_id;
                        }
                        break;
                    }
                }
            }
            if (!isset($log)) {
                $log = $testLogModel->where('test_attempt_id', $attemptIdParam)
                                    ->where('question_id', $questionId)
                                    ->first();
            }
        } else {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Missing identifiers']);
        }
        
        if (!$log) return $this->response->setJSON(['status' => 'error']);
        $logId = $log->id ?? $log->log_id;

        $attempt = $this->attemptModel->findCached($log->test_attempt_id);
        if (!$attempt || (string)$attempt->user_id !== (string)$userId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Unauthorized']);
        }

        if ($attempt->status == 3) {
            return $this->response->setJSON(['status' => 'kicked', 'message' => 'Ujian telah diselesaikan.']);
        }
        if ($attempt->status == 4) {
            return $this->response->setJSON(['status' => 'kicked', 'message' => 'Ujian telah dikunci.']);
        }

        // Validate generated_at timestamp for static exams (offline mode protection)
        $generatedAt = $this->request->getPost('generated_at');
        if ($generatedAt) {
            $test = $this->testModel->findCached($attempt->test_id);
            if ($test && $test->exam_mode === 'static') {
                $maxAge = 7 * 86400; // 7 days
                if (time() - (int)$generatedAt > $maxAge) {
                    return $this->response->setJSON([
                        'status' => 'error',
                        'message' => 'Halaman ujian statis sudah kadaluarsa. Hubungi pengawas.'
                    ]);
                }

                // Validate within exam time window
                $now = date('Y-m-d H:i:s');
                if ($test->begin_time && $now < $test->begin_time) {
                    return $this->response->setJSON([
                        'status' => 'error',
                        'message' => 'Ujian belum dimulai.'
                    ]);
                }
                if ($test->end_time && $now > $test->end_time) {
                    return $this->response->setJSON([
                        'status' => 'error',
                        'message' => 'Waktu ujian telah berakhir.'
                    ]);
                }
            }
        }

        session_write_close();

        $payload = [];
        if ($questionType == 3) {
            $answerText = $this->request->getPost('answer_text') ?? '';
            $sanitized = strip_tags($answerText);
            $payload['answer_text'] = mb_substr($sanitized, 0, 5000);
        } elseif ($questionType == 4 || $questionType == 5) {
            $payload['matching_answers'] = json_decode($this->request->getPost('matching_answers_json') ?? '{}', true) ?: [];
        } else {
            $selectedIds = $this->request->getPost('selected_answers') ?? [];
            if (!is_array($selectedIds)) $selectedIds = [$selectedIds];
            $payload['selected_answers'] = $selectedIds;
        }

        $attemptId = $log->test_attempt_id;
        $redisKey = "exam_answers:{$attemptId}";

        try {
            $redis = \App\Libraries\RedisClient::getInstance();
            if ($redis) {
                $redis->hSet($redisKey, $logId, json_encode($payload));
                $redis->expire($redisKey, 86400);
            }
        } catch (\Exception $e) {
            return $this->response->setJSON(['status' => 'error', 'message' => $e->getMessage()]);
        }

        $testLogModel->update($logId, ['answered_at' => date('Y-m-d H:i:s')]);

        try {
            $cache = service('cache');
            $cache->delete("attempt_questions_{$attemptId}");
            $cache->delete("attempt_answers_{$attemptId}");
        } catch (\Exception $e) {}

        return $this->response->setJSON(['status' => 'success', 'csrf_token' => csrf_hash()]);
    }

    /**
     * Auto-sync Redis to DB
     * POST /api/exam/auto-sync
     */
    public function autoSync()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $attemptId = $this->request->getPost('attempt_id');
        session_write_close();

        $attempt = $this->attemptModel->findCached($attemptId);
        if (!$attempt || (string)$attempt->user_id !== (string)$userId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Invalid attempt.']);
        }

        $this->flushRedisAnswersToDb($attemptId);
        
        $testModel = new \App\Models\TestModel();
        $test = $testModel->findCached($attempt->test_id);

        return $this->response->setJSON([
            'status' => 'success',
            'exam_mode' => $test ? $test->exam_mode : 'normal',
            'static_page_path' => $test ? $test->static_page_path : null
        ]);
    }

    /**
     * Finish exam
     * POST /api/exam/finish
     */
    public function finish()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $testId = $this->request->getPost('test_id');
        $attempt = $this->attemptModel->getActiveAttemptCached($testId, $userId);

        if ($attempt) {
            $this->flushRedisAnswersToDb($attempt->id);
            $scorer = new \App\Libraries\ScoringEngine();
            $scorer->calculateAndSaveScore($attempt->id);
            $this->activityLog->log('finish_test', $userId, 'test', $testId, 'Menyelesaikan ujian (static)');
        }

        return $this->response->setJSON([
            'status' => 'success',
            'message' => 'Ujian berhasil diselesaikan!',
            'redirect' => $testId ? (string)site_url('/student/results/view/' . $testId) : null
        ]);
    }

    /**
     * Check current score
     * POST /api/exam/check-score
     */
    public function checkScore()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $attemptId = $this->request->getPost('attempt_id');
        session_write_close();

        $attempt = $this->attemptModel->findCached($attemptId);
        if (!$attempt || (string)$attempt->user_id !== (string)$userId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Invalid attempt.']);
        }

        $this->flushRedisAnswersToDb($attemptId);
        $scorer = new \App\Libraries\ScoringEngine();
        $score = $scorer->calculateScorePreview($attemptId);

        return $this->response->setJSON(['status' => 'success', 'score' => $score]);
    }



    /**
     * Flush Redis answers to DB (same as ExamController)
     */
    private function flushRedisAnswersToDb($attemptId)
    {
        $examService = new \App\Libraries\ExamService();
        $examService->flushRedisAnswersToDb((int)$attemptId);
    }
}
