<?php

namespace App\Controllers\Api;

use App\Controllers\BaseController;
use App\Models\TestModel;
use App\Models\TestAttemptModel;
use App\Models\TestLogModel;
use App\Models\TestLogAnswerModel;
use App\Models\QuestionModel;
use App\Models\AnswerModel;
use App\Models\ActivityLogModel;

class ExamApiController extends BaseController
{
    protected TestModel $testModel;
    protected TestAttemptModel $attemptModel;
    protected ActivityLogModel $activityLog;

    public function __construct()
    {
        $this->testModel = new TestModel();
        $this->attemptModel = new TestAttemptModel();
        $this->activityLog = new ActivityLogModel();
    }

    /**
     * Initialize exam: authenticate, start attempt if needed, return questions JSON
     * POST /api/exam/init
     */
    public function init()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error', 'message' => 'Silakan login terlebih dahulu.']);
        }

        $testId = $this->request->getPost('test_id') ?? $this->request->getGet('test_id');
        if (!$testId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'test_id diperlukan.']);
        }

        $test = $this->testModel->findCached($testId);
        if (!$test || !$test->is_enabled) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Ujian tidak tersedia.']);
        }

        // Check for active attempt
        $attempt = $this->attemptModel->getActiveAttemptCached($testId, $userId);

        // Attempt terkunci: jangan kirim soal. Bundle memakai reason ini untuk
        // menampilkan layar "dikeluarkan" alih-alih halaman ujian.
        if ($attempt && (int) $attempt->status === 2) {
            return $this->response->setJSON([
                'status'  => 'error',
                'reason'  => 'ejected',
                'message' => 'Ujian Anda dihentikan oleh pengawas. Serahkan perangkat kepada pengawas.',
            ]);
        }

        // Jendela waktu hanya membatasi MEMULAI ujian. Sebelumnya dicek lebih
        // dulu, sehingga siswa yang sedang mengerjakan ikut terkunci begitu
        // end_time lewat -- attempt-nya masih berjalan tapi soalnya tidak bisa
        // dimuat lagi, dan tidak ada jalan keluar dari layar itu. Jalur web
        // (Student\ExamController::take) memang tidak pernah memblokir resume.
        if (!$attempt) {
            $now = date('Y-m-d H:i:s');
            if ($test->begin_time && $now < $test->begin_time) {
                return $this->response->setJSON(['status' => 'error', 'reason' => 'not_yet', 'message' => 'Ujian belum dimulai.']);
            }
            if ($test->end_time && $now > $test->end_time) {
                return $this->response->setJSON(['status' => 'error', 'reason' => 'closed', 'message' => 'Waktu ujian telah berakhir.']);
            }
        }

        if (!$attempt) {
            // Attempt must be generated by the backend prepare/start flow first.
            // Sertakan info gerbang password supaya klien (bundle kiosk) bisa
            // menampilkan form token ujian sebelum memanggil exam/start.
            return $this->response->setJSON([
                'status'            => 'need_prepare',
                'test_name'         => $test->name,
                'password_required' => !empty($test->password),
                // Isi layar persiapan, disamakan dengan student/exam/prepare
                // di web: durasi, batas lulus, pengulangan, petunjuk, dan
                // peringatan auto-submit.
                'test' => [
                    'id'                   => (int) $test->id,
                    'name'                 => $test->name,
                    'description'          => (string) ($test->description ?? ''),
                    'duration_minutes'     => (int) $test->duration_minutes,
                    'passing_score'        => (float) ($test->passing_score ?? 0),
                    'max_score'            => (float) ($test->max_score ?? 0),
                    'is_repeatable'        => (int) $test->is_repeatable,
                    'auto_submit_on_cheat' => (int) ($test->auto_submit_on_cheat ?? 0),
                    'begin_time'           => $test->begin_time,
                    'end_time'             => $test->end_time,
                ],
            ]);
        }

        $gate = \App\Libraries\KioskPresence::check($test, $attempt, (int) $userId);
        if (!$gate['ok']) {
            \App\Libraries\KioskPresence::audit((int) $test->id, (int) $userId, $gate['reason'], 'exam/init');
            return $this->response->setStatusCode(403)->setJSON([
                'status'  => 'error',
                'message' => \App\Libraries\KioskPresence::message(),
                'reason'  => 'kiosk_required',
            ]);
        }

        // Load questions and answers
        $db = \Config\Database::connect();
        $cache = service('cache');
        $questionsKey = "attempt_questions_{$attempt->id}";
        $questions = $cache->get($questionsKey);
        if ($questions === null) {
            $questions = $db->query("
                SELECT tl.id as log_id, tl.test_attempt_id, tl.question_id,
                       tl.question_text, tl.question_type, tl.question_difficulty,
                       tl.display_order, tl.num_answers, tl.answer_text, tl.is_unsure
                FROM test_logs tl
                WHERE tl.test_attempt_id = ?
                ORDER BY tl.display_order ASC
            ", [$attempt->id])->getResult();
            try {
                $cache->save($questionsKey, $questions, 7200); // 2 hours
            } catch (\Exception $e) {}
        }

        $logIds = array_column($questions, 'log_id');
        $answers = [];
        if (!empty($logIds)) {
            $answersKey = "attempt_answers_{$attempt->id}";
            $answers = $cache->get($answersKey);
            if ($answers === null) {
                $rawAnswers = $db->query("
                    SELECT tla.id as log_answer_id, tla.test_log_id, tla.answer_id,
                           tla.answer_text, tla.is_selected, tla.display_order, tla.position
                    FROM test_log_answers tla
                    WHERE tla.test_log_id IN ?
                    ORDER BY tla.display_order ASC
                ", [$logIds])->getResult();
                $answers = [];
                foreach ($rawAnswers as $ans) {
                    $answers[$ans->test_log_id][] = $ans;
                }
                try {
                    $cache->save($answersKey, $answers, 7200); // 2 hours
                } catch (\Exception $e) {}
            }
        }

        // Merge Redis cached answers
        try {
            $redis = \App\Libraries\RedisClient::getInstance();
            if ($redis) {
                $redisKey = "exam_answers:{$attempt->id}";
                $redisAnswers = $redis->hGetAll($redisKey);
                if (!empty($redisAnswers)) {
                    foreach ($questions as &$q) {
                        if (isset($redisAnswers[$q->log_id])) {
                            $saved = json_decode($redisAnswers[$q->log_id], true);
                            if ($q->question_type == 3) {
                                $q->answer_text = $saved['answer_text'] ?? '';
                            } elseif ($q->question_type == 4 || $q->question_type == 5) {
                                $q->answer_text = json_encode($saved['matching_answers'] ?? []);
                            } else {
                                $selectedIds = $saved['selected_answers'] ?? [];
                                if (isset($answers[$q->log_id])) {
                                    foreach ($answers[$q->log_id] as &$ans) {
                                        $ans->is_selected = in_array($ans->answer_id, $selectedIds) ? 1 : 0;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        } catch (\Exception $e) {
            log_message('error', 'Redis integration error in ExamApiController::take: ' . $e->getMessage());
        }

        // Build response
        $questionsData = [];
        $answersData = [];
        foreach ($questions as $q) {
            $qAnswers = [];
            if (isset($answers[$q->log_id])) {
                foreach ($answers[$q->log_id] as $a) {
                    $qAnswers[] = [
                        'log_answer_id' => (int)$a->log_answer_id,
                        'answer_id' => (int)$a->answer_id,
                        'answer_text' => $a->answer_text,
                        'display_order' => (int)$a->display_order,
                        'is_selected' => (int)$a->is_selected,
                    ];
                }
            }
            if ($test->exam_mode === 'static') {
                $answersData[$q->question_id] = $qAnswers;
                $questionsData[] = [
                    'question_id' => (int)$q->question_id,
                    'question_type' => (int)$q->question_type,
                    'display_order' => (int)$q->display_order,
                    'answer_text' => $q->answer_text,
                    // question_text wajib: bundle kiosk merender soal dari
                    // respon ini (halaman static web tidak menggunakannya).
                    'question_text' => $q->question_text,
                ];
            } else {
                $answersData[$q->log_id] = $qAnswers;
                
                $questionsData[] = [
                    'log_id' => (int)$q->log_id,
                    'question_text' => $q->question_text,
                    'question_type' => (int)$q->question_type,
                    'display_order' => (int)$q->display_order,
                    'num_answers' => (int)$q->num_answers,
                    'answer_text' => $q->answer_text,
                    'is_unsure' => (int)($q->is_unsure ?? 0),
                ];
            }
        }

        // Load anti-cheat settings
        $settingModel = new \App\Models\SettingModel();
        $userModel = new \App\Models\UserModel();
        $user = $userModel->find($userId);

        if (!$user || !(int)$user->is_active) {
            return $this->response->setStatusCode(403)->setJSON([
                'status' => 'error',
                'message' => 'Akun tidak aktif. Silakan hubungi pengawas ujian.',
                'action' => 'logout',
            ]);
        }

        $unbannedAt = $user->unbanned_at ?? null;
        $unbannedAtMs = !empty($unbannedAt) ? strtotime($unbannedAt) * 1000 : null;

        $wsToken = bin2hex(random_bytes(16));
        try {
            $redis = \App\Libraries\RedisClient::getInstance();
            if ($redis) {
                $redis->setex("ws_student_token:{$wsToken}", 14400, json_encode([
                    'user_id' => (int)$userId,
                    'attempt_id' => (int)$attempt->id,
                    'test_id' => (int)$test->id
                ]));
            }
        } catch (\Exception $e) {
            log_message('error', 'Redis error generating ws_student_token in API: ' . $e->getMessage());
        }

        return $this->response->setJSON([
            'status' => 'success',
            'attempt_id' => (int)$attempt->id,
            'ws_token' => $wsToken,
            'ws_url' => \App\Libraries\WebSocketUrl::resolve(),
            'user' => [
                'id' => (int)$userId,
                'username' => session('username'),
                'firstname' => session('firstname'),
                'lastname' => session('lastname'),
                'is_active' => (bool)$user->is_active,
                'unbanned_at' => $unbannedAt,
                'unbanned_at_ms' => $unbannedAtMs,
            ],
            'test' => [
                'id' => (int)$test->id,
                'name' => $test->name,
                'duration_minutes' => (int)$test->duration_minutes,
                'passing_score' => (float)$test->passing_score,
                'max_score' => (float)$test->max_score,
                'show_menu' => (int)$test->show_menu,
                'allow_noanswer' => (int)$test->allow_noanswer,
                'auto_logout_on_timeout' => (int)$test->auto_logout_on_timeout,
                'auto_submit_on_cheat' => (int)($test->auto_submit_on_cheat ?? 0),
                'started_at' => $attempt->started_at,
                'started_at_ms' => strtotime($attempt->started_at) * 1000,
                'begin_time_ms' => strtotime($test->begin_time) * 1000,
                'server_now_ms' => time() * 1000,
                'exam_mode' => $test->exam_mode,
                'static_page_path' => $test->static_page_path,
            ],
            'anti_cheat' => [
                'enabled' => (bool)$settingModel->getValue('anti_cheat_enabled', false),
                'auto_submit_on_cheat' => (bool)($test->auto_submit_on_cheat ?? false),
                'max_strikes' => (int)$settingModel->getValue('max_cheat_strikes', 2),
                'suspend_timer' => (int)$settingModel->getValue('suspend_timer_seconds', 30),
                'current_strikes' => (int)($attempt->cheat_strikes ?? 0),
                'is_banned' => (int)($attempt->cheat_strikes ?? 0) >= (int)$settingModel->getValue('max_cheat_strikes', 2),
                'unbanned_at_ms' => $unbannedAtMs,
                'title' => $settingModel->getValue('anti_cheat_title', '⚠️ Peringatan Kecurangan!'),
                'message' => $settingModel->getValue('anti_cheat_message', 'Sistem mendeteksi Anda meninggalkan halaman ujian.'),
                'logo' => $settingModel->getValue('anti_cheat_logo', ''),
            ],
            'questions' => $questionsData,
            'answers' => $answersData,
            'csrf_token' => csrf_hash(),
            'csrf_name' => csrf_token(),
        ]);
    }



    /**
     * Start exam: generate attempt (replica of Student\ExamController::start as JSON)
     * POST /api/exam/start
     */
    public function start()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error', 'message' => 'Silakan login terlebih dahulu.']);
        }

        $testId = (int) ($this->request->getPost('test_id') ?? 0);
        if ($testId <= 0) {
            return $this->response->setStatusCode(400)->setJSON(['status' => 'error', 'message' => 'test_id diperlukan.']);
        }

        $test = $this->testModel->findCached($testId);
        if (!$test || !$test->is_enabled) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Ujian tidak valid.']);
        }

        $password = (string) ($this->request->getPost('password') ?? '');
        if (!empty($test->password) && !hash_equals($test->password, $password)) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Password ujian salah.']);
        }

        $activeAttempt = $this->attemptModel->getActiveAttemptCached($testId, $userId);
        if ($activeAttempt) {
            return $this->response->setJSON(['status' => 'success', 'attempt_id' => (int) $activeAttempt->id, 'resumed' => true]);
        }

        if (empty($test->is_repeatable)) {
            $completed = $this->attemptModel->where('user_id', $userId)
                                             ->where('test_id', $testId)
                                             ->whereIn('status', [3, 4])
                                             ->first();
            if ($completed) {
                return $this->response->setJSON(['status' => 'error', 'message' => 'Ujian ini hanya dapat dikerjakan satu kali.']);
            }
        }

        $examService = new \App\Libraries\ExamService();
        $attempt = $examService->generateAttempt($testId, (int) $userId, $this->request->getIPAddress());

        if (!$attempt) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Ujian ini hanya dapat dikerjakan satu kali atau terjadi kesalahan saat menyiapkan ujian.']);
        }

        $this->activityLog->log('start_exam', $userId, 'test', $testId, 'Memulai ujian (kiosk bundle)');

        return $this->response->setJSON(['status' => 'success', 'attempt_id' => (int) $attempt->id, 'resumed' => false]);
    }

    /**
     * Save answer via AJAX (same as ExamController::saveAnswer but JSON-only)
     * POST /api/exam/autosave
     */
    public function autosave()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error', 'message' => 'Unauthorized']);
        }

        $logId = $this->request->getPost('log_id');
        $questionId = $this->request->getPost('question_id');
        $attemptIdParam = $this->request->getPost('attempt_id');
        $questionType = $this->request->getPost('question_type');

        if (!$this->passesKioskGate((int) $attemptIdParam, (int) $userId, 'exam/autosave')) {
            return $this->response->setStatusCode(403)->setJSON([
                'status'  => 'error',
                'message' => \App\Libraries\KioskPresence::message(),
                'reason'  => 'kiosk_required',
            ]);
        }

        $testLogModel = new TestLogModel();
        
        if ($logId) {
            $log = $testLogModel->findCached($logId);
        } elseif ($questionId && $attemptIdParam) {
            $cache = service('cache');
            $cachedQuestions = $cache->get("attempt_questions_{$attemptIdParam}");
            if ($cachedQuestions) {
                foreach ($cachedQuestions as $q) {
                    if ((string)($q->question_id ?? '') === (string)$questionId) {
                        $log = $q;
                        if (!isset($log->id) && isset($log->log_id)) {
                            $log->id = $log->log_id;
                        }
                        break;
                    }
                }
            }
            if (!isset($log)) {
                $log = $testLogModel->where('test_attempt_id', $attemptIdParam)
                                    ->where('question_id', $questionId)
                                    ->first();
            }
        } else {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Missing identifiers']);
        }
        
        if (!$log) return $this->response->setJSON(['status' => 'error']);
        $logId = $log->id ?? $log->log_id;

        $attempt = $this->attemptModel->find($log->test_attempt_id);
        if (!$attempt || (string)$attempt->user_id !== (string)$userId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Unauthorized']);
        }

        // Status 2 = attempt dikunci (pelanggaran atau tindakan pengawas).
        // Sebelumnya hanya 3 dan 4 yang ditolak, sehingga siswa yang sudah
        // dikunci -- termasuk lewat ban -- tetap bisa menyimpan jawaban.
        if ((int) $attempt->status === 2) {
            return $this->response->setJSON([
                'status'  => 'kicked',
                'reason'  => 'locked',
                'message' => 'Ujian Anda dihentikan oleh pengawas.',
            ]);
        }

        if ($attempt->status == 3) {
            return $this->response->setJSON(['status' => 'kicked', 'message' => 'Ujian telah diselesaikan.']);
        }
        if ($attempt->status == 4) {
            return $this->response->setJSON(['status' => 'kicked', 'message' => 'Ujian telah dikunci.']);
        }

        // Server-side time validation: reject saves after duration expires
        $test = $this->testModel->findCached($attempt->test_id);
        if ($test && $test->duration_minutes > 0 && $attempt->started_at) {
            $elapsedSeconds = time() - strtotime($attempt->started_at);
            $allowedSeconds = ($test->duration_minutes * 60) + 60; // 60 seconds grace period
            if ($elapsedSeconds > $allowedSeconds) {
                return $this->response->setJSON(['status' => 'kicked', 'message' => 'Waktu ujian telah habis.']);
            }
        }

        // Validate generated_at timestamp for static exams (offline mode protection).
        // Hanya nilai numerik yang divalidasi: nilai non-numerik dulu di-cast jadi 0
        // sehingga selalu dianggap kadaluarsa dan jawaban ditolak diam-diam.
        $generatedAt = $this->request->getPost('generated_at');
        if (is_numeric($generatedAt)) {
            $test = $this->testModel->findCached($attempt->test_id);
            if ($test && $test->exam_mode === 'static') {
                $maxAge = 7 * 86400; // 7 days
                if (time() - (int)$generatedAt > $maxAge) {
                    return $this->response->setJSON([
                        'status' => 'error',
                        'message' => 'Halaman ujian statis sudah kadaluarsa. Hubungi pengawas.'
                    ]);
                }

                // Validate within exam time window
                $now = date('Y-m-d H:i:s');
                if ($test->begin_time && $now < $test->begin_time) {
                    return $this->response->setJSON([
                        'status' => 'error',
                        'message' => 'Ujian belum dimulai.'
                    ]);
                }
                if ($test->end_time && $now > $test->end_time) {
                    return $this->response->setJSON([
                        'status' => 'error',
                        'message' => 'Waktu ujian telah berakhir.'
                    ]);
                }
            }
        }

        $payload = [];
        if ($questionType == 3) {
            $answerText = $this->request->getPost('answer_text') ?? '';
            $sanitized = strip_tags($answerText);
            $payload['answer_text'] = mb_substr($sanitized, 0, 5000);
        } elseif ($questionType == 4 || $questionType == 5) {
            $jsonStr = (string)($this->request->getPost('matching_answers_json') ?? '{}');
            if (strlen($jsonStr) > 10000) $jsonStr = '{}';
            $payload['matching_answers'] = json_decode($jsonStr, true, 50) ?: [];
        } else {
            $selectedIds = $this->request->getPost('selected_answers') ?? [];
            if (!is_array($selectedIds)) $selectedIds = [$selectedIds];
            $payload['selected_answers'] = $selectedIds;
        }

        $attemptId = $log->test_attempt_id;
        $redisKey = "exam_answers:{$attemptId}";

        try {
            $redis = \App\Libraries\RedisClient::getInstance();
            if (!$redis) {
                // FAIL-CLOSED: Redis unavailable — refuse to silently drop the answer.
                // The frontend will show an error toast and retry automatically.
                log_message('critical', "[FAIL-CLOSED] autosave: Redis unavailable for attempt #{$attemptId}, log #{$logId}. Answer NOT saved.");
                return $this->response->setStatusCode(503)->setJSON([
                    'status'  => 'error',
                    'message' => 'Sistem penyimpanan sementara tidak dapat diakses. Jawaban Anda belum tersimpan. Mohon tunggu sebentar dan coba kirim ulang.',
                ]);
            }
            $redis->hSet($redisKey, $logId, json_encode($payload));
            $redis->expire($redisKey, 86400);
        } catch (\Exception $e) {
            log_message('critical', "[FAIL-CLOSED] autosave: Redis exception for attempt #{$attemptId}, log #{$logId}: " . $e->getMessage());
            return $this->response->setStatusCode(503)->setJSON([
                'status'  => 'error',
                'message' => 'Sistem penyimpanan sementara tidak dapat diakses. Jawaban Anda belum tersimpan. Mohon tunggu sebentar dan coba kirim ulang.',
            ]);
        }

        $testLogModel->update($logId, ['answered_at' => date('Y-m-d H:i:s')]);

        try {
            $cache = service('cache');
            $cache->delete("attempt_questions_{$attemptId}");
            $cache->delete("attempt_answers_{$attemptId}");
        } catch (\Exception $e) {}

        return $this->response->setJSON(['status' => 'success', 'csrf_token' => csrf_hash()]);
    }

    /**
     * Auto-sync Redis to DB
     * POST /api/exam/auto-sync
     */
    public function autoSync()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $attemptId = $this->request->getPost('attempt_id');

        $attempt = $this->attemptModel->find($attemptId);
        if (!$attempt || (string)$attempt->user_id !== (string)$userId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Invalid attempt.']);
        }

        // Status 2 = attempt dikunci (pelanggaran atau tindakan pengawas).
        // Sebelumnya hanya 3 dan 4 yang ditolak, sehingga siswa yang sudah
        // dikunci -- termasuk lewat ban -- tetap bisa menyimpan jawaban.
        if ((int) $attempt->status === 2) {
            return $this->response->setJSON([
                'status'  => 'kicked',
                'reason'  => 'locked',
                'message' => 'Ujian Anda dihentikan oleh pengawas.',
            ]);
        }

        if (!$this->passesKioskGate((int) $attemptId, (int) $userId, 'exam/auto-sync')) {
            return $this->response->setStatusCode(403)->setJSON([
                'status'  => 'error',
                'message' => \App\Libraries\KioskPresence::message(),
                'reason'  => 'kiosk_required',
            ]);
        }

        $this->flushRedisAnswersToDb($attemptId);
        
        $testModel = new \App\Models\TestModel();
        $test = $testModel->findCached($attempt->test_id);

        return $this->response->setJSON([
            'status' => 'success',
            'exam_mode' => $test ? $test->exam_mode : 'normal',
            'static_page_path' => $test ? $test->static_page_path : null
        ]);
    }

    /**
     * Finish exam
     * POST /api/exam/finish
     */
    public function finish()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $testId = $this->request->getPost('test_id');
        $attempt = $this->attemptModel->getActiveAttemptCached($testId, $userId);

        if ($attempt && !$this->passesKioskGate((int) $attempt->id, (int) $userId, 'exam/finish')) {
            return $this->response->setStatusCode(403)->setJSON([
                'status'  => 'error',
                'message' => \App\Libraries\KioskPresence::message(),
                'reason'  => 'kiosk_required',
            ]);
        }

        if ($attempt && (int) $attempt->status === 2) {
            return $this->response->setJSON([
                'status'  => 'kicked',
                'reason'  => 'locked',
                'message' => 'Ujian Anda dihentikan oleh pengawas.',
            ]);
        }

        if ($attempt) {
            $this->flushRedisAnswersToDb($attempt->id);
            $scorer = new \App\Libraries\ScoringEngine();
            $scorer->calculateAndSaveScore($attempt->id);
            $this->activityLog->log('finish_test', $userId, 'test', $testId, 'Menyelesaikan ujian (static)');
        }

        return $this->response->setJSON([
            'status' => 'success',
            'message' => 'Ujian berhasil diselesaikan!',
            'redirect' => $testId ? (string)site_url('/student/results/view/' . $testId) : null
        ]);
    }

    /**
     * Check current score
     * POST /api/exam/check-score
     */
    public function checkScore()
    {
        $userId = session('user_id');
        if (!$userId) {
            return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
        }

        $attemptId = $this->request->getPost('attempt_id');

        $attempt = $this->attemptModel->find($attemptId);
        if (!$attempt || (string)$attempt->user_id !== (string)$userId) {
            return $this->response->setJSON(['status' => 'error', 'message' => 'Invalid attempt.']);
        }

        // Status 2 = attempt dikunci (pelanggaran atau tindakan pengawas).
        // Sebelumnya hanya 3 dan 4 yang ditolak, sehingga siswa yang sudah
        // dikunci -- termasuk lewat ban -- tetap bisa menyimpan jawaban.
        if ((int) $attempt->status === 2) {
            return $this->response->setJSON([
                'status'  => 'kicked',
                'reason'  => 'locked',
                'message' => 'Ujian Anda dihentikan oleh pengawas.',
            ]);
        }

        $this->flushRedisAnswersToDb($attemptId);
        $scorer = new \App\Libraries\ScoringEngine();
        $score = $scorer->calculateScorePreview($attemptId);

        return $this->response->setJSON(['status' => 'success', 'score' => $score]);
    }

    /**
     * Report cheating
     * POST /api/exam/report-cheat
     */
    public function reportCheat()
    {
        try {
            $userId = session('user_id');
            if (!$userId) {
                return $this->response->setStatusCode(401)->setJSON(['status' => 'error']);
            }

            $attemptId = $this->request->getPost('attempt_id');
            $cheatType = $this->request->getPost('type') ?? 'unknown';

            $examService = new \App\Libraries\ExamService();
            $result = $examService->handleCheat((int)$attemptId, (int)$userId, $cheatType);

            return $this->response->setJSON($result);
        } catch (\Throwable $e) {
            log_message('error', 'reportCheat ERROR: ' . $e->getMessage());
            return $this->response->setStatusCode(500)->setJSON([
                'status' => 'error',
                'message' => 'An internal error occurred while reporting.'
            ]);
        }
    }





    /**
     * Gerbang kiosk untuk endpoint yang hanya memegang attempt_id.
     * Mengembalikan true bila ujian boleh ditulis dari klien ini.
     */
    private function passesKioskGate(int $attemptId, int $userId, string $endpoint): bool
    {
        if ($attemptId <= 0) {
            return true;
        }
        $attempt = $this->attemptModel->find($attemptId);
        if (!$attempt || (string) $attempt->user_id !== (string) $userId) {
            return true; // bukan urusan gerbang ini; endpoint punya cek sendiri
        }
        $test = $this->testModel->findCached($attempt->test_id);

        $gate = \App\Libraries\KioskPresence::check($test, $attempt, $userId);
        if (!$gate['ok']) {
            \App\Libraries\KioskPresence::audit((int) $attempt->test_id, $userId, $gate['reason'], $endpoint);
            return false;
        }
        return true;
    }

    /**
     * Flush Redis answers to DB (same as ExamController)
     */
    private function flushRedisAnswersToDb($attemptId)
    {
        $examService = new \App\Libraries\ExamService();
        $examService->flushRedisAnswersToDb((int)$attemptId);
    }
}
