server {
    listen 80;
    listen [::]:80;
    
    # Catch-all server name
    server_name _;

    root /var/www/html/public;
    index index.php index.html index.htm;

    access_log /var/log/nginx/sistem_ujian_access.log;
    error_log /var/log/nginx/sistem_ujian_error.log;

    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~* \.(ico|css|js|gif|jpeg|jpg|png|woff|ttf|otf|svg|woff2|eot)$ {
        expires 30d;
        access_log off;
        add_header Cache-Control "public";
    }
}
